<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var string $style
 * @var string $locale
 * @var array $defaults
 * @var bool $bibliographic
 * @var bool $append_site
 * @var bool $append_date
 * @var string $tag
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');

if (is_null($style)):
    $style = 'chicago-fullnote-bibliography';
endif;

try {
    $style = @\Seboettg\CiteProc\StyleSheet::loadStyleSheet($style);
} catch (\Seboettg\CiteProc\Exception\CiteProcException $e) {
    $style = null;
}

if ($style):

    $citeProc = new \Seboettg\CiteProc\CiteProc($style, $locale);
    $csl = $this->rdfToCsl($resource, $defaults);
    // CiteProc fails when the metadata are incomplete.
    try {
        $citation = @$citeProc->render([$csl], 'bibliography');
    } catch (\Exception $e) {
        $vars = $this->vars();
        $vars->offsetSet('style', '');
        echo $this->partial('common/citation', $this->vars());
        return;
    }
    $citation = mb_substr($citation, 52, -13);

else:

    // Format: only pseudo-Chicago is managed when there is no csl.

    $citation = '';

    $creators = $resource->value('dcterms:creator', ['all' => true]) ?: (@$defaults['dcterms:creator'][0]['@value'] ? [$defaults['dcterms:creator'][0]['@value']] : []);
    // Strip formatting and remove empty creator elements.
    $creators = array_values(array_filter(array_map('strip_tags', $creators)));
    if ($creators) {
        switch (count($creators)):
        case 1:
            $creator = $creators[0];
            break;
        case 2:
            // Chicago-style item citation: two authors.
            $creator = sprintf($translate('%1$s and %2$s'), $creators[0], $creators[1]);
            break;
        case 3:
            // Chicago-style item citation: three authors.
            $creator = sprintf($translate('%1$s, %2$s, and %3$s'), $creators[0], $creators[1], $creators[2]);
            break;
        default:
            // Chicago-style item citation: more than three authors.
            $creator = sprintf($translate('%s et al.'), $creators[0]);
            break;
        endswitch;
        $citation .= $creator;
    }

    $title = $resource->displayTitle();
    $citation .= ($citation ? ', ' : '') . '“' . $title . '”';

    $publisher = $resource->value('dcterms:publisher') ?: @$defaults['dcterms:publisher'][0]['@value'];
    if ($publisher):
        $citation .= ', <i>' . $publisher . '</i>';
    endif;

    $date = $resource->value('dcterms:date') ?: @$defaults['dcterms:date'][0]['@value'];
    if ($date):
        $citation .= ', ' . $date;
    endif;

endif;

if ($append_site || $append_date):
    $citation = rtrim($citation, '. ');

    if ($append_site):
        if ($site = $this->viewModel()->getRoot()->getVariable('site')):
            $citation .= ', <i>' . $site->title() . '</i>';
        endif;
    endif;

    if ($append_date):
        $accessed = $escape($this->i18n()->dateFormat(new \DateTime(), \Omeka\View\Helper\I18n::DATE_FORMAT_LONG));
        $url = '<span class="citation-url">' . $escape($resource->siteUrl(null, true)) . '</span>';
        // Chicago-style item citation: access date and URL.
        $citation .= ', ' . sprintf($translate('accessed %1$s, %2$s'), $accessed, $url);
    endif;

endif;

echo empty($tag) ? $citation : "<$tag class=\"citation\">$citation</$tag>";
