<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\ItemRepresentation[] $resources
 * @var string $query
 * @var array $options
 */

$plugins = $this->getHelperPluginManager();
$citation = $plugins->get('citation');

$options['tag'] = 'li';
?>

<div class="block block-bibliography">
    <ul>
    <?php foreach ($resources as $resource): ?>
        <?= $citation($resource, $options) ?>
    <?php endforeach; ?>
    </ul>
</div>
